name: Build and Release

on:
  push:
    tags:
      - 'v*' # Trigger on version tags

# Add permissions block
permissions:
  contents: write # This is required for creating releases

jobs:
  build:
    name: Build on ${{ matrix.os }} for ${{ matrix.arch }}
    runs-on: ubuntu-22.04  # Changed from ubuntu-20.04 to ubuntu-22.04
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            arch: x86_64
            artifact_name: apt2discord-x86_64
          - os: ubuntu-22.04
            arch: aarch64
            artifact_name: apt2discord-arm64

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up QEMU
      if: matrix.arch == 'aarch64'
      uses: docker/setup-qemu-action@v3
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'  # Updated to Python 3.10 which comes with Ubuntu 22.04
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller requests

    - name: Build binary (x86_64)
      if: matrix.arch == 'x86_64'
      run: |
        pyinstaller --name ${{ matrix.artifact_name }} --onefile apt2discord.py

    - name: Build binary (ARM64)
      if: matrix.arch == 'aarch64'
      uses: uraimo/run-on-arch-action@v2
      with:
        arch: aarch64
        distro: ubuntu22.04  # Changed to Ubuntu 22.04
        install: |
          apt-get update
          apt-get install -y python3-pip python3-dev
        run: |
          pip3 install pyinstaller requests
          pyinstaller --name ${{ matrix.artifact_name }} --onefile apt2discord.py
          
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/${{ matrix.artifact_name }}
        draft: false
        prerelease: false
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 